  <!-- Framework CSS -->
  <link rel='stylesheet' href='$context_path$/blueprint/screen.css' type='text/css' media='screen, projection'> 
  <link rel='stylesheet' href='$context_path$/blueprint/print.css' type='text/css' media='print'> 
  <!--[if lt IE 8]><link rel='stylesheet' href='$context_path$/blueprint/ie.css' type='text/css' media='screen, projection'><![endif]--> 
  
  <!-- Import fancy-type plugin for the sample page. --> 
  <link rel='stylesheet' href='$context_path$/blueprint/plugins/fancy-type/screen.css' type='text/css' media='screen, projection'>
  
  <!-- CSS for Blogjure -->
  <link rel='stylesheet' href='$context_path$/css/blogjure.css' type='text/css' media='screen, projection'>
